// <auto-generated />
using System;
using ContosoUniversity.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContosoUniversity.EF.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20260109142246_Contoso_V1")]
    partial class Contoso_V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContosoUniversity.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Credits = 3,
                            Title = "Chemistry"
                        },
                        new
                        {
                            Id = 2,
                            Credits = 3,
                            Title = "Microeconomics"
                        },
                        new
                        {
                            Id = 3,
                            Credits = 3,
                            Title = "Macroeconomics"
                        },
                        new
                        {
                            Id = 4,
                            Credits = 4,
                            Title = "Calculus"
                        },
                        new
                        {
                            Id = 5,
                            Credits = 4,
                            Title = "Trigonometry"
                        },
                        new
                        {
                            Id = 6,
                            Credits = 3,
                            Title = "Composition"
                        },
                        new
                        {
                            Id = 7,
                            Credits = 4,
                            Title = "Literature"
                        });
                });

            modelBuilder.Entity("ContosoUniversity.Entities.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Grade = 0,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            Grade = 2,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            Grade = 1,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 4,
                            Grade = 1,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 5,
                            Grade = 1,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 6,
                            Grade = 1,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 1,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 2,
                            Grade = 1,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 1,
                            Grade = 1,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 6,
                            Grade = 1,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 7,
                            Grade = 1,
                            StudentId = 6
                        });
                });

            modelBuilder.Entity("ContosoUniversity.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PhotoUri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnrollmentDate = new DateTime(2010, 8, 31, 22, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Carson",
                            LastName = "Alexander"
                        },
                        new
                        {
                            Id = 2,
                            EnrollmentDate = new DateTime(2012, 8, 31, 22, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Meredith",
                            LastName = "Alonso"
                        },
                        new
                        {
                            Id = 3,
                            EnrollmentDate = new DateTime(2013, 8, 31, 22, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Arturo",
                            LastName = "Anand"
                        },
                        new
                        {
                            Id = 4,
                            EnrollmentDate = new DateTime(2012, 8, 31, 22, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Gytis",
                            LastName = "Barzdukas"
                        },
                        new
                        {
                            Id = 5,
                            EnrollmentDate = new DateTime(2012, 8, 31, 22, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Yan",
                            LastName = "Li"
                        },
                        new
                        {
                            Id = 6,
                            EnrollmentDate = new DateTime(2011, 8, 31, 22, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Peggy",
                            LastName = "Justice"
                        },
                        new
                        {
                            Id = 7,
                            EnrollmentDate = new DateTime(2013, 8, 31, 22, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Laura",
                            LastName = "Norman"
                        },
                        new
                        {
                            Id = 8,
                            EnrollmentDate = new DateTime(2005, 8, 31, 22, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Nino",
                            LastName = "Olivetto"
                        });
                });

            modelBuilder.Entity("ContosoUniversity.Entities.Enrollment", b =>
                {
                    b.HasOne("ContosoUniversity.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContosoUniversity.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ContosoUniversity.Entities.Student", b =>
                {
                    b.OwnsOne("ContosoUniversity.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("StudentId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("StudentId");

                            b1.ToTable("Students");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("ContosoUniversity.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("ContosoUniversity.Entities.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
